version: '3'
services:
  application:
    container_name: app
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DB_SCHEMA: public
      DB_HOST: 'database'
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - 3000:3000

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
